# Generated by Django 3.0.5 on 2020-05-25 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_auto_20200525_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
    ]
